stages:
  - clone
  - build

variables:
  REPO: 'https://github.com/ukrsite/kbot'
  BRANCH: 'main'

parameters:
  - name: 'OS'
    type: 'choice'
    choices:
      - 'linux'
      - 'darwin'
      - 'windows'
      - 'all'
    default: 'linux'
    description: 'Pick OS'

  - name: 'ARCH'
    type: 'choice'
    choices:
      - 'amd64'
      - 'arm'
      - 'arm64'
    default: 'amd64'
    description: 'Pick Architecture'

clone:
  stage: clone
  script:
    - echo 'Cloning the repository'
    - git clone --branch $BRANCH $REPO

build:
  stage: build
  script:
    - echo "Build for platform $OS $ARCH"
    - make build TARGETOS=$OS TARGETARCH=$ARCH
