# Default values for helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
autoscaling:
  enabled: false
replicaCount: 1
image:
  registry: "ghcr.io"
  repository: "ukrsite/kbot"
  tag: "v1.0.5-3f22f4b"
  os: linux
  arch: amd64
secret:
  name: "kbot"
  env: "TELE_TOKEN"
  key: "token"
securityContext:
  privileged: true
